
The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1


The following have been reloaded with a version change:
  1) zlib/1.2.11 => zlib/1.2.11_parallel_studio-2017.1


The following have been reloaded with a version change:
  1) hdf5/1.8.18 => hdf5/1.8.18_parallel_studio-2017.1
  2) szip/2.1.1 => szip/2.1.1_parallel_studio-2017.1
  3) zlib/1.2.11_parallel_studio-2017.1 => zlib/1.2.11


The following have been reloaded with a version change:
  1) hdf5/1.8.18_parallel_studio-2017.1 => hdf5/1.8.18
  2) openmpi/2.0.1_parallel_studio-2017.1 => openmpi/2.1.2_gcc-4.8.5
  3) python/3.7.0 => python/2.7.14_openmpi-2.1.2
  4) szip/2.1.1_parallel_studio-2017.1 => szip/2.1.1

/Users/apensoneault/asynch_python/asynch_py/io.py:286: RuntimeWarning: divide by zero encountered in double_scalars
  return (np.sqrt(data.shape[1])/np.sqrt(data.shape[1]-1))*np.sqrt(np.sum((data-mean)**2*weight,axis=1))
/Users/apensoneault/asynch_python/asynch_py/io.py:286: RuntimeWarning: invalid value encountered in multiply
  return (np.sqrt(data.shape[1])/np.sqrt(data.shape[1]-1))*np.sqrt(np.sum((data-mean)**2*weight,axis=1))
/Users/apensoneault/asynch_python/asynch_py/io.py:320: RuntimeWarning: invalid value encountered in maximum
  m_out = np.expand_dims(['%.4f' %  np.maximum(mean_current - std_current,0)],axis=1)
/Users/apensoneault/asynch_python/asynch_py/io.py:362: RuntimeWarning: invalid value encountered in maximum
  m_out = np.expand_dims(['%.4f' %  np.maximum(mean_current - std_current,0)],axis=1)
